# Copyright (c) 2020-2023 by the Zeek Project. See LICENSE for details.
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: checkbashisms
    name: Check for bashisms in /bin/sh scripts
    entry: ./tests/Scripts/3rdparty/checkbashisms.pl
    language: script
    types: ["sh"]

  # - id: autogen-docs
  #   name: Check that generated documentation is up-to-date
  #   entry: ./doc/scripts/autogen-docs
  #   language: script
  #   pass_filenames: false

  - id: stray_baselines
    name: Check for stray BTest baselines
    entry: ./tests/Scripts/stray_baselines.py
    language: python
    pass_filenames: false

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v16.0.3'
  hooks:
  - id: clang-format
    types: ["c", "c++"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: '^tests/Baseline'
  - id: end-of-file-fixer
    exclude: '^tests/Baseline|^doc/autogen|^doc/_static'
  - id: check-yaml
  - id: check-added-large-files

- repo: https://gitlab.com/daverona/pre-commit/cpp
  rev: 0.8.0
  hooks:
  - id: cpplint
    exclude: '3rdparty/|node-factory.autogen.h'
    args: ["--quiet"]

- repo: https://github.com/jorisroovers/gitlint
  rev:  v0.19.1
  hooks:
  - id: gitlint

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
  - id: cmake-lint

- repo: https://github.com/crate-ci/typos
  rev: v1.14.8
  hooks:
  - id: typos
    exclude: 'tests/.*/regexp/.*'

exclude: 3rdparty/|doc/(autogen|.*examples)/|/Baseline/|(\.svg$)|(\.dat$)
